version: "3.3"
services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - ./firefly_iii_upload:/var/www/html/storage/upload
    env_file: stack.env
    #ports:
    #  - 8080:8080
    depends_on:
      - db
  db:
    image: mariadb:10.8.2
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - ./firefly_iii_db:/var/lib/mysql
  cron:
    image: alpine
    command: sh -c "echo \"0 3 * * * wget
      https://firefly.my.domain/api/v1/cron/5e57c095224f6f4239b52a4bc493687a\" |
      crontab - && crond -f -L /dev/stdout"
