version: "3.9"
services:
  dockge:
    image: louislam/dockge:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /docker_data/:/docker_data
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/docker_data
    networks:
      vlan200:
        ipv4_address: 172.16.20.28

networks:
  vlan200:
    external: true
