version: "3.9"
services:
  speedtest-tracker:
    restart: unless-stopped
    container_name: speedtest-tracker
    image: lscr.io/linuxserver/speedtest-tracker:latest
    volumes:
      - ./data:/config
    networks:
      vlan200:
        ipv4_address: 172.16.20.17
networks:
  vlan200:
    external: true
