version: '3.3'

services:
  vikunja:
    image: vikunja/vikunja
    container_name: vikunja
    environment:
      VIKUNJA_SERVICE_PUBLICURL: http://someurl:3456/
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: somepass1
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: passpass
      VIKUNJA_MAILER_ENABLED: 1
      VIKUNJA_MAILER_HOST: email.relay.something
      VIKUNJA_MAILER_PORT: 25
    volumes:
      - ./files:/app/vikunja/files
    ports:
      - "3456:3456"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:10
    container_name: vikunja-db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_USER: vikunja
      MYSQL_PASSWORD: somepass1
      MYSQL_DATABASE: vikunja
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"]
      interval: 2s
