---
version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://bookstack.something
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=somepass
      - DB_DATABASE=bookstackapp
      - MAIL_DRIVER=smtp
      - MAIL_HOST=email.relay
      - MAIL_PORT=25
      - MAIL_FROM=bookstack@some.server
    volumes:
      - ./data:/config
    ports:
      - 6875:443
    restart: always
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=<yourdbpass>
      - TZ=Europe/Ljubljana
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=somepass
    volumes:
      - ./db:/config
    restart: always

    diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    restart: always
    volumes:
      - /run/user/1010/docker.sock:/var/run/docker.sock
      - ./diun:/diun # Path to store Diun's data
    environment:
      - "TZ=Europe/Ljubljana"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_NOTIF_MAIL_HOST=smtp.gmail.com"
      - "DIUN_NOTIF_MAIL_PORT=587"
      - "DIUN_NOTIF_MAIL_SSL=false"
      - "DIUN_NOTIF_MAIL_LOCALNAME=xxx"
      - "DIUN_NOTIF_MAIL_USERNAME=xxx@gmail.com"
      - "DIUN_NOTIF_MAIL_PASSWORD=pxxx"
      - "DIUN_NOTIF_MAIL_FROM=xxx@gmail.com"
      - "DIUN_NOTIF_MAIL_TO=xxx@gmail.com"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 * 11 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
